tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/certs/mkcert+2.pem"
        keyFile: "/etc/certs/mkcert+2-key.pem"

http:
  middlewares:
    keycloak:
      forwardAuth:
        address: "https://traefik-forward-auth.docker.localhost"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"
