version: '3.7'

services:

  rethinkdb:
    image: "rethinkdb:2.4.1-buster-slim"
    command: "rethinkdb --bind all --initial-password ${RETHINKDB_PASSWORD}"
    networks:
      - private_databases
      - public
    volumes:
      - rethinkdb_data:/data
    ports:
      - target: 28015
        published: 28015
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # GLOBAL
        - traefik.enable=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # PORT
        - traefik.http.services.rethinkdb.loadbalancer.server.port=8080
        # HTTP
        - traefik.http.routers.rethinkdb-http.entrypoints=insecure
        - traefik.http.routers.rethinkdb-http.rule=Host(`rethinkdb.docker.localhost`)
        - traefik.http.routers.rethinkdb-http.middlewares=https-redirect@docker
        # HTTPS
        - traefik.http.routers.rethinkdb-https.entrypoints=secure
        - traefik.http.routers.rethinkdb-https.rule=Host(`rethinkdb.docker.localhost`)
        - traefik.http.routers.rethinkdb-https.tls=true

  postgres:
    image: "bitnami/postgresql:11-debian-10"
    environment:
      POSTGRESQL_USERNAME: "${POSTGRESQL_USERNAME}"
      POSTGRESQL_PASSWORD: "${POSTGRESQL_PASSWORD}"
    networks:
      - private_databases
      - public
    volumes:
      - postgres_data:/bitnami/postgresql
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    networks:
      - private_databases
      - public
    volumes:
       - pgadmin_data:/root/.pgadmin
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # GLOBAL
        - traefik.enable=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # PORT
        - traefik.http.services.pgadmin.loadbalancer.server.port=80
        # HTTP
        - traefik.http.routers.pgadmin-http.entrypoints=insecure
        - traefik.http.routers.pgadmin-http.rule=Host(`pgadmin.docker.localhost`)
        - traefik.http.routers.pgadmin-http.middlewares=https-redirect@docker
        # HTTPS
        - traefik.http.routers.pgadmin-https.entrypoints=secure
        - traefik.http.routers.pgadmin-https.rule=Host(`pgadmin.docker.localhost`)
        - traefik.http.routers.pgadmin-https.tls=true

volumes:

  rethinkdb_data:
  postgres_data:
  pgadmin_data:

networks:

  private_databases:
    driver: overlay
    name: private_databases
  public:
    external: true
