version: '3.7'

services:

  scope:
    image: weaveworks/scope:1.13.1
    networks:
      - private_portainer
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - works.weave.role=system

        - traefik.enable=true
        - traefik.http.services.weave-scope.loadbalancer.server.port=4040

        - traefik.http.routers.weave-scope-http.entrypoints=insecure
        - traefik.http.routers.weave-scope-http.rule=Host(`weave-scope.docker.localhost`)

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.weave-scope-http.middlewares=https-redirect@docker

        - traefik.http.routers.weave-scope-https.entrypoints=secure
        - traefik.http.routers.weave-scope-https.rule=Host(`weave-scope.docker.localhost`)
        - traefik.http.routers.weave-scope-https.tls=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"

  agent:
    image: portainer/agent:1.6.0
    environment:
      LOG_LEVEL: debug
      AGENT_PORT: 9001
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - private_portainer
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:1.24.0-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password '$$2y$$05$$v/MgPft4FUgD772S1VenouFjpChwYUCYvxUxAQHIaV/0kE/RWHBy2'
    volumes:
      - portainer_data:/data
    networks:
      - private_portainer
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.portainer.loadbalancer.server.port=9000

        - traefik.http.routers.portainer-http.entrypoints=insecure
        - traefik.http.routers.portainer-http.rule=Host(`portainer.docker.localhost`)

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.portainer-http.middlewares=https-redirect@docker

        - traefik.http.routers.portainer-https.entrypoints=secure
        - traefik.http.routers.portainer-https.rule=Host(`portainer.docker.localhost`)
        - traefik.http.routers.portainer-https.tls=true

volumes:

  portainer_data:

networks:

  private_portainer:
    driver: overlay
    name: private_portainer
  public:
    external: true
