version: '3.7'

services:

  traefik-forward-auth:
    image: funkypenguin/traefik-forward-auth
    environment:
      - CLIENT_ID=traefik-auth
      - CLIENT_SECRET="<random_secret>"
      - OIDC_ISSUER=https://auth.docker.localhost/auth/realms/master
      - SECRET=LH49wCZ4ZijgUTfm8etb
      - AUTH_HOST=auth.docker.localhost
      - COOKIE_DOMAINS=docker.localhost
      - LOG_LEVEL=debug
    networks:
      - private_security
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # GLOBAL
        - traefik.enable=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # PORT
        - traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181
        # HTTP
        - traefik.http.routers.traefik-forward-auth-http.entrypoints=insecure
        - traefik.http.routers.traefik-forward-auth-http.rule=Host(`traefik-forward-auth.docker.localhost`)
        - traefik.http.routers.traefik-forward-auth-http.middlewares=https-redirect@docker
        # HTTPS
        - traefik.http.routers.traefik-forward-auth-https.entrypoints=secure
        - traefik.http.routers.traefik-forward-auth-https.rule=Host(`traefik-forward-auth.docker.localhost`)
        - traefik.http.routers.traefik-forward-auth-https.tls=true

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: infra
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: infra
      KEYCLOAK_HOSTNAME: auth.docker.localhost
      KEYCLOAK_ALWAYS_HTTPS: "true"
    networks:
      - private_security
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # GLOBAL
        - traefik.enable=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # PORT
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        # HTTP
        - traefik.http.routers.keycloak-http.entrypoints=insecure
        - traefik.http.routers.keycloak-http.rule=Host(`keycloak.docker.localhost`)
        - traefik.http.routers.keycloak-http.middlewares=https-redirect@docker
        # HTTPS
        - traefik.http.routers.keycloak-https.entrypoints=secure
        - traefik.http.routers.keycloak-https.rule=Host(`keycloak.docker.localhost`)
        - traefik.http.routers.keycloak-https.tls=true

  openldap:
    image: osixia/openldap:1.4.0
    environment:
      LDAP_ORGANISATION: localhost
      LDAP_DOMAIN: docker.localhost
      LDAP_ADMIN_PASSWORD: infra
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_TLS: "false"
    networks:
      - private_security
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - var_lib_ldap:/var/lib/ldap
      - etc_ldap_slapd:/etc/ldap/slapd.d

  ldap-user-manager:
    image: wheelybird/ldap-user-manager:v1.2
    environment:
      NO_HTTPS: "TRUE"
      LDAP_URI: ldap://openldap:389
      LDAP_BASE_DN: dc=docker,dc=localhost
      LDAP_ADMINS_GROUP: admins
      LDAP_ADMIN_BIND_DN: cn=admin,dc=docker,dc=localhost
      LDAP_ADMIN_BIND_PWD: infra
    networks:
      - private_security
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # GLOBAL
        - traefik.enable=true
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # PORT
        - traefik.http.services.ldap-user-manager.loadbalancer.server.port=80
        # HTTP
        - traefik.http.routers.ldap-user-manager-http.entrypoints=insecure
        - traefik.http.routers.ldap-user-manager-http.rule=Host(`ldap-user-manager.docker.localhost`)
        - traefik.http.routers.ldap-user-manager-http.middlewares=https-redirect@docker
        # HTTPS
        - traefik.http.routers.ldap-user-manager-https.entrypoints=secure
        - traefik.http.routers.ldap-user-manager-https.rule=Host(`ldap-user-manager.docker.localhost`)
        - traefik.http.routers.ldap-user-manager-https.tls=true

networks:

  private_security:
    driver: overlay
    name: private_security
  public:
    external: true

volumes:

  var_lib_ldap:
  etc_ldap_slapd:
