version: '3.7'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: infra
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: infra
      KEYCLOAK_HOSTNAME: keycloak.docker.localhost
      KEYCLOAK_ALWAYS_HTTPS: "true"
    networks:
      - private_security
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.keycloak.loadbalancer.server.port=8080

        - traefik.http.routers.keycloak-http.entrypoints=insecure
        - traefik.http.routers.keycloak-http.rule=Host(`keycloak.docker.localhost`)

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.keycloak-http.middlewares=https-redirect@docker

        - traefik.http.routers.keycloak-https.entrypoints=secure
        - traefik.http.routers.keycloak-https.rule=Host(`keycloak.docker.localhost`)
        - traefik.http.routers.keycloak-https.tls=true

  openldap:
    image: osixia/openldap:1.4.0
    environment:
      LDAP_ORGANISATION: localhost
      LDAP_DOMAIN: docker.localhost
      LDAP_ADMIN_PASSWORD: infra
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_TLS: "false"
    networks:
      - private_security
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - var_lib_ldap:/var/lib/ldap
      - etc_ldap_slapd:/etc/ldap/slapd.d

  ldap-user-manager:
    image: wheelybird/ldap-user-manager:v1.2
    environment:
      NO_HTTPS: "TRUE"
      LDAP_URI: ldap://openldap:389
      LDAP_BASE_DN: dc=docker,dc=localhost
      LDAP_ADMINS_GROUP: admins
      LDAP_ADMIN_BIND_DN: cn=admin,dc=docker,dc=localhost
      LDAP_ADMIN_BIND_PWD: infra
    networks:
      - private_security
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.ldap-manager.loadbalancer.server.port=80

        - traefik.http.routers.ldap-manager-http.entrypoints=insecure
        - traefik.http.routers.ldap-manager-http.rule=Host(`ldap-manager.docker.localhost`)

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.ldap-manager-http.middlewares=https-redirect@docker

        - traefik.http.routers.ldap-manager-https.entrypoints=secure
        - traefik.http.routers.ldap-manager-https.rule=Host(`ldap-manager.docker.localhost`)
        - traefik.http.routers.ldap-manager-https.tls=true

networks:

  private_security:
    driver: overlay
    name: private_security
  public:
    external: true

volumes:

  var_lib_ldap:
  etc_ldap_slapd:
